version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - backend

  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./php:/var/www
    networks:
      - backend

networks:
  backend:
    driver: bridge